version: '3.7'

services:
  db:
    container_name: iotsens-postgress
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
      - ./docker/database/99999999__mock_data.sql:/docker-entrypoint-initdb.d/99999999__mock_data.sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iotsens_db

  app:
    container_name: iotsens-app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/iotsens_db?user=user&password=password